apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: meudeployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: site
        image: heliobrandao/conversao-temperatura:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: web-page
spec:
  selector:
    app: web
  ports:
    - port: 80
      protocol: TCP
      nodePort: 30000
  type: NodePort
